name = "SpectralVis"
uuid = "7d2a520e-4adf-42bb-b581-af58f1f37afc"
authors = ["Manuel Lohmann"]
version = "0.1.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
